### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [hanluong/NimbleiOSChallenge#1]
Hello Han 👋 , thank you for your effort on the code submission. I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by hanluong** [comment]
Hi Mike,

I’m very happy to correct these issues and improve my code in review
process with you but I can’t start right now because I have some personal
reasons in this weekend. Can I start to review and responses issues on
Monday?

Thank you so much,
Han Luong

Vào Th 7, 28 thg 10, 2023 lúc 14:07 Pham Le Minh ***@***.***>
đã viết:

**Comment by minhnimble** [comment]
Hi, Han 👋

For your information, I completed the 1st round of review just now. Regarding the timeline, I am fine with your plan to handle the issues on Monday. Please note that the target is to conclude everything by the end of Tuesday, thus it would be best if you could address the issues before that time. 

Have a great weekend!

**Comment by hanluong** [comment]
Thanks Mike, have a nice weekend too!

Vào Th 7, 28 thg 10, 2023 lúc 16:10 Pham Le Minh ***@***.***>
đã viết:

**Comment by hanluong** [comment]
Hi Mike,

I got error with the credentials API that Nimble give me before. Can you help me to check these keys are still valid?
Thank you!

**Comment by minhnimble** [comment]
Hello Han,

As discussed in the email thread, the provided example email/password should not be used as the testing accounts because it is subjected to change. Therefore, feel free to make use of the registration API we provided for creating your test account.

**Comment by hanluong** [comment]
Yes, I had already created my account using registration API.

**Comment by hanluong** [comment]
Hi Mike,

I updated these issues. Although there are two issues, I think I will skip them later.
Thank you for your time!

**Comment by minhnimble** [comment]
Good morning, Han ☀️

Thank you for your timely updates! As of now, my review for this code challenge session has concluded, and thus no more submissions will be needed from your end. For the next step, you will hear from the Talent Acquisition team about the decision as soon as we complete the evaluation.
