### ISSUE TITLE
[Bug] Unable to navigate back when clicking on Start Survey button in the Survey Details screen

### ISSUE THREAD

**Issue by minhnimble** [hanluong/NimbleiOSChallenge#10]
## Issue
Once the users enter the Thank You screen, there is no way for the users to go back to the Home screen. The users have to restart the application at this point to continue using it.

Example screenshot:
<img src="https://github.com/hanluong/NimbleiOSChallenge/assets/70877098/bd620e85-bc3e-4bf2-ab83-9a163d0a464d" width="300">

## Expect

The Thank You screen should be dismissable once tapping on it, or it can be dismissed after a specific time (1 second).

**Comment by hanluong** [comment]
- Auto navigation back to Survey when finished.
Pull request - https://github.com/hanluong/NimbleiOSChallenge/pull/15
