### ISSUE TITLE
[Improvement] Application environments handling

### ISSUE THREAD

**Issue by minhnimble** [hanluong/NimbleiOSChallenge#4]
As per our API [documentation](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#ios), there are two environments that our API can support: `Staging` and `Production`. Now, you handle these environments by setting the `ROOT_URL` settings based on the configurations (Debug/Release), and it is not the best practice for managing this kind of task.

![Screenshot 2023-10-28 at 14 28 27](https://github.com/hanluong/NimbleiOSChallenge/assets/70877098/aa463c47-e577-4497-abd7-625ca8e5147b)

Thus, I would like to know more about your knowledge on this topic. Do you know any better approach to handle this? If yes, please update the project with some implementation examples. 🙂

By the way, do you have any experience handling DevOps (CI/CD) for different environments? Please brief me on the potential steps in a distribution pipeline per the environment setup.

**Comment by hanluong** [comment]
- Support multiples app environments (Debug, Staging, Release)
Pull request - https://github.com/hanluong/NimbleiOSChallenge/pull/17

- Added multiple configurations for different environments (Debug | Staging | Release), so that DevOps (CI/CD) can use them to distribute the app.
