### ISSUE TITLE
[Feature] Handle when there is an error from the API on Login screen

### ISSUE THREAD

**Issue by minhnimble** [hanluong/NimbleiOSChallenge#8]
## Issue

When the user provides an invalid combination of email and password or attempts to log in to the application without any connection, there is no handling or a visible prompt on the application to let the user know what is currently happening. As a result, it is quite confusing for the user on what to do next to log in successfully.

- Provide an invalid combination of email and password:

https://github.com/hanluong/NimbleiOSChallenge/assets/70877098/56cea965-4318-4fa8-bb17-35c3f41caac3

## Expect

Error cases should be visibly handled on the application and let the user know what is happening.

**Comment by hanluong** [comment]
- Handle errors from the login API 
Pull request - https://github.com/hanluong/NimbleiOSChallenge/pull/12
