### ISSUE TITLE
[Bug] The survey item content on the Home screen is difficult to see and doesn't match with the design

### ISSUE THREAD

**Issue by minhnimble** [hanluong/NimbleiOSChallenge#9]
## Issue

The application needs to show the survey list after loading all the data with a valid logged-in session-like design. Currently, there are a few UI problems with a survey item on the Home screen:

- The display image for each survey item is very blurry.
- The left indentation between the survey title and the page indicator isn't properly aligned per design.
- The vertical spacing between the survey title and the page indicator is too far apart compared to the design.
- The date shows a fixed day instead of the actual date.

Example screenshot:
  <img src="https://github.com/hanluong/NimbleiOSChallenge/assets/70877098/d911e344-1ab7-4e0a-aa8a-7d815a4b7f07" width="300">

## Expect

- The survey item should look clearer and identical to the design:
  <img src="https://user-images.githubusercontent.com/70877098/159682538-5934d10f-fd97-4c01-b95a-28b0c6199ed8.png" width="300">

- Regarding the date, it should be able to show the current date instead of a hard-coded date.

**Comment by hanluong** [comment]
> The display image for each survey item is very blurry.
- The API return **cover_image_url** is too small. Therefore, the background image was blurred.


- Update left indentation between the survey title and the page indicator
- Update vertical spacing between the survey title and the page indicator
- Shows current date
Pull request - https://github.com/hanluong/NimbleiOSChallenge/pull/14
![Simulator Screenshot - iPhone 14 - 2023-10-30 at 14 02 17](https://github.com/hanluong/NimbleiOSChallenge/assets/67725137/8cac4a0e-4eac-4534-91ba-73cee4eeba66)

**Comment by minhnimble** [comment]
@hanluong 

> The API return cover_image_url is too small. Therefore, the background image was blurred.

→ Nice spot. Just sharing here again in case you miss, the API can support high res images with instructions [here](https://documenter.getpostman.com/view/11835486/UVsPNPfU#064357a5-4625-4ef7-b042-0d1f7e2f2acb) from Postman. 😁

**Comment by hanluong** [comment]
> @hanluong
> 
> > The API return cover_image_url is too small. Therefore, the background image was blurred.
> 
> → Nice spot. Just sharing in case you miss, the API can support high res images with instructions [here](https://documenter.getpostman.com/view/11835486/UVsPNPfU#064357a5-4625-4ef7-b042-0d1f7e2f2acb) from Postman. 😁

Yeah, I didn't see it. Thank you!
